import React, { useMemo, useState } from 'react';
import {
  BarChart, Bar, LineChart, Line, AreaChart, Area,
  ComposedChart, XAxis, YAxis, CartesianGrid,
  Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell, LabelList
} from 'recharts';
import { BarChart2, TrendingUp, Table2, PieChart as PieIcon, Layers } from 'lucide-react';

/**
 * DataTableChart – renders GFM markdown table as interactive chart.
 * Supports: bar, line, area/miền, combined (bar+line dual Y), pie/tròn.
 * Auto-detects chart type from first context line AND pivots year-column tables.
 */

type ViewMode = 'table' | 'bar' | 'line' | 'area' | 'combined' | 'pie';

interface TableData {
  headers: string[];
  rows: string[][];
}

// ── Markdown parser ───────────────────────────────────────────────────────────
function parseMarkdownTable(md: string): TableData | null {
  // Normalize flattened markdown tables generated by AI using structured output
  // e.g., "| col1 | col2 ||---|---|| val1 | val2 |" -> "| col1 | col2 |\n|---|---|\n| val1 | val2 |"
  let normalizedMd = md.replace(/\|\|/g, '|\n|');

  // If the first line has text preceding the table, like "Biểu đồ: Kết hợp| Chỉ tiêu |", split it before the first pipe.
  normalizedMd = normalizedMd.replace(/^(.*?)(?=\|)/m, match => {
    return match.trim() ? match + '\n' : match;
  });

  const lines = normalizedMd.split('\n').map(l => l.trim()).filter(l => l.startsWith('|'));
  if (lines.length < 3) return null;
  const parseRow = (line: string) =>
    line.replace(/^\||\|$/g, '').split('|').map(c => c.trim());
  const sepIdx = lines.findIndex(l =>
    l.replace(/^\||\|$/g, '').split('|').every(c => /^\s*:?-+:?\s*$/.test(c))
  );
  if (sepIdx < 1) return null;
  const headers = parseRow(lines[sepIdx - 1]);
  const rows = lines.slice(sepIdx + 1).map(parseRow);
  if (rows.length === 0 || headers.length < 2) return null;
  return { headers, rows };
}

// Parse a cell to number, return NaN if not numeric
function parseNum(raw: string): number {
  let s = String(raw).trim().replace(/\s/g, '').replace('%', '');
  if (s.includes(',') && !s.includes('.')) {
    s = s.replace(/,/g, '.');
  } else if (s.includes('.') && s.includes(',')) {
    if (s.lastIndexOf(',') > s.lastIndexOf('.')) {
      s = s.replace(/\./g, '').replace(',', '.');
    } else {
      s = s.replace(/,/g, '');
    }
  } else if (s.match(/^\d{1,3}(\.\d{3})+$/)) {
    s = s.replace(/\./g, '');
  }
  return parseFloat(s);
}

// Detect if column headers (after label/unit cols) are years (e.g. 2000-2030)
function isYearHeader(h: string): boolean {
  const n = parseInt(h.replace(/[^0-9]/g, ''));
  return !isNaN(n) && n >= 1990 && n <= 2040;
}

// ── Pivot logic ───────────────────────────────────────────────────────────────
// When table has: | Chỉ tiêu | Đơn vị | 2015 | 2020 | 2024 |
// rows are indicators, columns are years → pivot so year becomes X-axis name
// Output: [{ name: "2015", "Giá trị SX CN (Tỷ đồng)": 2800, "Tốc độ TT (%)": 9.5 }, ...]
interface ChartRow { name: string;[key: string]: string | number }

function buildChartData(table: TableData): { data: ChartRow[]; keys: string[]; needsPivot: boolean } {
  const { headers, rows } = table;

  // Find which columns are year-columns
  const yearCols = headers.slice(1).map((h, i) => ({ h, i: i + 1, isYear: isYearHeader(h) }));
  const hasYears = yearCols.filter(c => c.isYear).length >= 2;

  // Check if ALSO has a unit column (header[1] is "Đơn vị" / "Unit" / "ĐVT")
  const hasUnitCol = /đơn vị|unit|đvt/i.test(headers[1] || '');

  if (hasYears) {
    // PIVOT: rows = indicators, year columns → time-series
    const labelCol = 0;
    const unitCol = hasUnitCol ? 1 : -1;
    const dataCols = yearCols.filter(c => c.isYear);

    // For combined chart: split keys into primary (large values) vs secondary (small % values)
    const seriesKeys: string[] = rows.map(row => {
      const name = row[labelCol];
      const unit = unitCol >= 0 ? row[unitCol] : '';
      return unit ? `${name} (${unit})` : name;
    });

    const pivotedData: ChartRow[] = dataCols.map(yc => {
      const obj: ChartRow = { name: yc.h };
      rows.forEach((row, ri) => {
        const raw = row[yc.i] || '';
        const num = parseNum(raw);
        obj[seriesKeys[ri]] = isNaN(num) ? raw : num;
      });
      return obj;
    });

    const numericKeys = seriesKeys.filter(k =>
      pivotedData.some(d => typeof d[k] === 'number')
    );

    return { data: pivotedData, keys: numericKeys, needsPivot: true };
  } else {
    // No pivot: row[0] = X-axis name, other columns = series
    const data: ChartRow[] = rows.map(row => {
      const obj: ChartRow = { name: row[0] || '' };
      headers.slice(1).forEach((h, i) => {
        const num = parseNum(row[i + 1] || '');
        obj[h] = isNaN(num) ? (row[i + 1] || '') : num;
      });
      return obj;
    });
    const keys = headers.slice(1).filter(h =>
      data.some(d => typeof d[h] === 'number')
    );
    return { data, keys, needsPivot: false };
  }
}

// ── Chart type detection ──────────────────────────────────────────────────────
function detectChartType(content: string): ViewMode {
  const first = content.split('\n')[0].toLowerCase();
  if (/kết hợp|combined|cột.*đường|đường.*cột/.test(first)) return 'combined';
  if (/miền|area/.test(first)) return 'area';
  if (/tròn|pie|cơ cấu|structure/.test(first)) return 'pie';
  if (/đường|line|tốc độ|xu hướng|trend/.test(first)) return 'line';
  return 'bar';
}

// ── Colors ────────────────────────────────────────────────────────────────────
const COLORS = ['#6366f1', '#10b981', '#f59e0b', '#ef4444', '#3b82f6', '#8b5cf6', '#ec4899'];

// ── Chart type button config ──────────────────────────────────────────────────
const CHART_BUTTONS: { v: ViewMode; label: string; Icon: any; color: string; border: string; bg: string; bgActive: string }[] = [
  { v: 'table', label: 'Bảng số liệu', Icon: Table2, color: '#6366f1', border: '#a5b4fc', bg: '#eef2ff', bgActive: '#6366f1' },
  { v: 'bar', label: 'Biểu đồ cột', Icon: BarChart2, color: '#10b981', border: '#6ee7b7', bg: '#ecfdf5', bgActive: '#10b981' },
  { v: 'line', label: 'Biểu đồ đường', Icon: TrendingUp, color: '#f59e0b', border: '#fde68a', bg: '#fffbeb', bgActive: '#f59e0b' },
  { v: 'area', label: 'Biểu đồ miền', Icon: Layers, color: '#0ea5e9', border: '#7dd3fc', bg: '#f0f9ff', bgActive: '#0ea5e9' },
  { v: 'combined', label: 'Kết hợp', Icon: BarChart2, color: '#8b5cf6', border: '#c4b5fd', bg: '#f5f3ff', bgActive: '#8b5cf6' },
  { v: 'pie', label: 'Biểu đồ tròn', Icon: PieIcon, color: '#f43f5e', border: '#fda4af', bg: '#fff1f2', bgActive: '#f43f5e' },
];

// ── Main component ────────────────────────────────────────────────────────────
export default function DataTableChart({ content }: { content: string }) {
  const suggestedView = useMemo(() => detectChartType(content), [content]);
  const [view, setView] = useState<ViewMode>(suggestedView);

  const table = useMemo(() => parseMarkdownTable(content), [content]);

  const { data: chartData, keys: numericKeys, needsPivot } = useMemo(
    () => table ? buildChartData(table) : { data: [], keys: [], needsPivot: false },
    [table]
  );

  const canChart = numericKeys.length > 0 && chartData.length >= 2;
  const canCombined = numericKeys.length >= 2;

  // Separate keys based on terminology/regex for combined charts
  const barKeys: string[] = [];
  const lineKeys: string[] = [];
  numericKeys.forEach(k => {
    if (/%|tốc độ|tỉ trọng|tỉ lệ/i.test(k)) {
      lineKeys.push(k);
    } else {
      barKeys.push(k);
    }
  });

  const annotation = useMemo(() => {
    const lines = content.split('\n');
    return lines.filter(l => !l.trim().startsWith('|') && l.trim()).join(' ').trim();
  }, [content]);

  if (!table) {
    return <p className="text-sm text-slate-600 whitespace-pre-wrap leading-relaxed">{content}</p>;
  }

  const xProps = {
    dataKey: 'name',
    tick: { fontSize: 11, fill: '#64748b' },
    angle: chartData.length > 6 ? -30 : 0,
    textAnchor: (chartData.length > 6 ? 'end' : 'middle') as 'end' | 'middle',
    height: chartData.length > 6 ? 50 : 30,
  };
  const yFmt = (v: any) => typeof v === 'number' ? v.toLocaleString('vi-VN') : v;
  const margin = { top: 10, right: 40, left: 10, bottom: 30 };

  return (
    <div className="space-y-3 w-full">
      {/* Toggle buttons — inline styles used intentionally to prevent Tailwind purge */}
      {canChart && (
        <div className="flex items-center gap-2 flex-wrap">
          {CHART_BUTTONS.filter(b => b.v !== 'combined' || canCombined).map(({ v, label, Icon, color, border, bg, bgActive }) => {
            const isActive = view === v;
            return (
              <button
                key={v}
                onClick={() => setView(v)}
                style={{
                  display: 'flex', alignItems: 'center', gap: '6px',
                  padding: '6px 12px', borderRadius: '8px',
                  fontSize: '12px', fontWeight: 700,
                  border: `1px solid ${isActive ? bgActive : border}`,
                  background: isActive ? bgActive : bg,
                  color: isActive ? '#fff' : color,
                  cursor: 'pointer', transition: 'all 0.15s',
                }}
              >
                <Icon size={12} /> {label}
              </button>
            );
          })}
        </div>
      )}

      {/* Table */}
      {view === 'table' && (
        <div className="overflow-x-auto rounded-xl border border-indigo-200 shadow-sm">
          <table className="text-sm border-collapse w-full" style={{ minWidth: 'max-content' }}>
            <thead>
              <tr className="bg-indigo-600 text-white">
                {table.headers.map((h, i) => (
                  <th key={i} className="px-4 py-2.5 border border-indigo-500 text-center whitespace-nowrap font-bold text-sm">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {table.rows.map((row, ri) => (
                <tr key={ri} className={ri % 2 === 0 ? 'bg-white' : 'bg-indigo-50/40'}>
                  {table.headers.map((_, ci) => (
                    <td key={ci} className={`px-4 py-2 border border-indigo-100 text-center whitespace-nowrap text-sm ${ci === 0 ? 'font-semibold text-slate-700 text-left' : 'text-slate-600 tabular-nums font-medium'}`}>
                      {row[ci] ?? '—'}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Bar chart */}
      {canChart && view === 'bar' && (
        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={chartData} margin={margin}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis {...xProps} />
              <YAxis tick={{ fontSize: 11, fill: '#64748b' }} width={65} tickFormatter={yFmt} />
              <Tooltip content={<CustomTooltip />} />
              <Legend wrapperStyle={{ fontSize: 11, paddingTop: 8 }} />
              {numericKeys.map((k, i) => (
                <Bar key={k} dataKey={k} fill={COLORS[i % COLORS.length]} radius={[3, 3, 0, 0]} maxBarSize={60}>
                  <LabelList dataKey={k} position="top" style={{ fontSize: 10, fill: '#64748b' }} formatter={yFmt} />
                </Bar>
              ))}
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Line chart */}
      {canChart && view === 'line' && (
        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
          <ResponsiveContainer width="100%" height={260}>
            <LineChart data={chartData} margin={margin}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis {...xProps} />
              <YAxis tick={{ fontSize: 11, fill: '#64748b' }} width={65} tickFormatter={yFmt} />
              <Tooltip content={<CustomTooltip />} />
              <Legend wrapperStyle={{ fontSize: 11, paddingTop: 8 }} />
              {numericKeys.map((k, i) => (
                <Line key={k} type="monotone" dataKey={k} stroke={COLORS[i % COLORS.length]} strokeWidth={2.5} dot={{ r: 4 }} activeDot={{ r: 6 }}>
                  <LabelList dataKey={k} position="top" style={{ fontSize: 10, fill: '#64748b' }} formatter={yFmt} />
                </Line>
              ))}
            </LineChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Area / Miền — stacked when multiple series */}
      {canChart && view === 'area' && (
        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
          <ResponsiveContainer width="100%" height={260}>
            <AreaChart data={chartData} margin={margin}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis {...xProps} />
              <YAxis tick={{ fontSize: 11, fill: '#64748b' }} width={65} tickFormatter={yFmt} />
              <Tooltip content={<CustomTooltip />} />
              <Legend wrapperStyle={{ fontSize: 11, paddingTop: 8 }} />
              {numericKeys.map((k, i) => (
                <Area key={k} type="monotone" dataKey={k}
                  stroke={COLORS[i % COLORS.length]} fill={COLORS[i % COLORS.length]}
                  fillOpacity={0.3} strokeWidth={2} stackId={numericKeys.length > 2 ? 'a' : undefined} />
              ))}
            </AreaChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Combined: bar (left Y) + line(s) (right Y) — ideal for value+rate tables */}
      {canChart && canCombined && view === 'combined' && (
        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
          <p className="text-[11px] text-slate-500 mb-2 font-medium">
            {barKeys.length > 0 && <><span className="text-indigo-600 font-bold">{barKeys.join(', ')}</span> — cột (trục trái)</>}
            {barKeys.length > 0 && lineKeys.length > 0 && " | "}
            {lineKeys.length > 0 && <><span className="text-amber-600 font-bold">{lineKeys.join(', ')}</span> — đường (trục phải)</>}
          </p>
          <ResponsiveContainer width="100%" height={290}>
            <ComposedChart data={chartData} margin={margin}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis {...xProps} />
              {barKeys.length > 0 && <YAxis yAxisId="left" tick={{ fontSize: 11, fill: '#64748b' }} width={70} tickFormatter={yFmt} />}
              {lineKeys.length > 0 && <YAxis yAxisId="right" orientation="right" tick={{ fontSize: 11, fill: '#f59e0b' }} width={55} tickFormatter={yFmt} />}
              <Tooltip content={<CustomTooltip />} />
              <Legend wrapperStyle={{ fontSize: 11, paddingTop: 8 }} />
              {barKeys.map((k, i) => (
                <Bar key={k} yAxisId="left" dataKey={k} fill={COLORS[i % COLORS.length]} radius={[3, 3, 0, 0]} maxBarSize={65} name={k}>
                  <LabelList dataKey={k} position="top" style={{ fontSize: 10, fill: '#64748b' }} formatter={yFmt} />
                </Bar>
              ))}
              {lineKeys.map((k, i) => (
                <Line key={k} yAxisId="right" type="monotone" dataKey={k}
                  stroke={COLORS[(i + barKeys.length) % COLORS.length]}
                  strokeWidth={2.5} dot={{ r: 4 }} activeDot={{ r: 6 }} name={k}>
                  <LabelList dataKey={k} position="top" style={{ fontSize: 10, fill: '#64748b' }} formatter={yFmt} />
                </Line>
              ))}
            </ComposedChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Pie / Tròn — displays multiple pies if multiple years/series exist */}
      {canChart && view === 'pie' && (
        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
          <div className={`grid gap-4 ${needsPivot ? (chartData.length > 2 ? 'grid-cols-1 md:grid-cols-2' : chartData.length === 2 ? 'grid-cols-2' : 'grid-cols-1') : (numericKeys.length > 2 ? 'grid-cols-1 md:grid-cols-2' : numericKeys.length === 2 ? 'grid-cols-2' : 'grid-cols-1')}`}>
            {needsPivot ? chartData.map((row, i) => (
              <div key={i} className="flex flex-col items-center">
                <ResponsiveContainer width="100%" height={260}>
                  <PieChart>
                    <Pie
                      data={numericKeys.map(k => ({ name: k, value: typeof row[k] === 'number' ? row[k] : 0 }))}
                      cx="50%" cy="50%" outerRadius={80}
                      dataKey="value"
                      label={({ name, percent }) => `${(percent * 100).toFixed(1)}%`}
                      labelLine
                    >
                      {numericKeys.map((_, idx) => <Cell key={idx} fill={COLORS[idx % COLORS.length]} />)}
                    </Pie>
                    <Tooltip formatter={(v: any) => typeof v === 'number' ? v.toLocaleString('vi-VN') : v} />
                    <Legend wrapperStyle={{ fontSize: 10, paddingTop: 8 }} />
                  </PieChart>
                </ResponsiveContainer>
                <p className="font-bold text-slate-700 text-sm mt-1 text-center">{row.name}</p>
              </div>
            )) : numericKeys.map((k, i) => (
              <div key={i} className="flex flex-col items-center">
                <ResponsiveContainer width="100%" height={260}>
                  <PieChart>
                    <Pie
                      data={chartData.map(d => ({ name: d.name, value: typeof d[k] === 'number' ? d[k] : 0 }))}
                      cx="50%" cy="50%" outerRadius={80}
                      dataKey="value"
                      label={({ name, percent }) => `${(percent * 100).toFixed(1)}%`}
                      labelLine
                    >
                      {chartData.map((_, idx) => <Cell key={idx} fill={COLORS[idx % COLORS.length]} />)}
                    </Pie>
                    <Tooltip formatter={(v: any) => typeof v === 'number' ? v.toLocaleString('vi-VN') : v} />
                    <Legend wrapperStyle={{ fontSize: 10, paddingTop: 8 }} />
                  </PieChart>
                </ResponsiveContainer>
                <p className="font-bold text-slate-700 text-sm mt-1 text-center">{k}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Annotation / source */}
      {annotation && (
        <p className="text-[11px] text-slate-400 italic leading-relaxed">{annotation}</p>
      )}
    </div>
  );
}

const CustomTooltip = ({ active, payload, label }: any) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-white border border-slate-200 rounded-xl p-3 shadow-xl text-sm">
      <p className="font-bold text-slate-800 mb-1">{label}</p>
      {payload.map((p: any, i: number) => (
        <p key={i} style={{ color: p.fill || p.stroke || p.color }}>
          {p.name}: <span className="font-bold">
            {typeof p.value === 'number' ? p.value.toLocaleString('vi-VN') : p.value}
          </span>
        </p>
      ))}
    </div>
  );
};
